# Generated by Django 4.2.2 on 2023-07-09 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_patient_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="phone",
        ),
    ]
