version: '3.3'
services:

 postgres:
   image: postgres:latest
   environment:
     - POSTGRES_DB=django
     - POSTGRES_USER=django
     - POSTGRES_PASSWORD=django
     - POSTGRES_PORT=5432

 redis:
    image: redis:latest

 django:
   build: .
   ports:
     - "8000:8000"
   volumes:
     - ./:/app/
   depends_on:
     - postgres
     - redis
   environment:
     - REDIS_HOST=redis
     - POSTGRESQL_ENGINE=django.db.backends.postgresql
     - POSTGRESQL_HOST=postgres
     - POSTGRESQL_PASSWORD=django
     - POSTGRESQL_NAME=django
     - POSTGRESQL_USER=django
     - DEBUG=True
     - SECRET_KEY=secret_key
   command: |
     python shop/manage.py runserver 0.0.0.0:8000

 worker:
   build: .
   volumes:
     - ./:/app/
   depends_on:
     - postgres
     - redis
   environment:
     - REDIS_HOST=redis
     - POSTGRESQL_ENGINE=django.db.backends.postgresql
     - POSTGRESQL_HOST=postgres
     - POSTGRESQL_PASSWORD=django
     - POSTGRESQL_NAME=django
     - POSTGRESQL_USER=django
     - DEBUG=True
     - SECRET_KEY=secret_key
   command: |
     python shop/manage.py rqworker