# Generated by Django 4.2.2 on 2023-06-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("diagnosis", "0001_initial"),
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="schedule",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="schedule.schedule"
            ),
        ),
    ]
