# Generated by Django 4.2.2 on 2023-07-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="day",
            field=models.DateField(
                blank=True,
                choices=[
                    ("2023-07-01", "2023-07-01"),
                    ("2023-07-02", "2023-07-02"),
                    ("2023-07-03", "2023-07-03"),
                    ("2023-07-04", "2023-07-04"),
                    ("2023-07-05", "2023-07-05"),
                    ("2023-07-06", "2023-07-06"),
                    ("2023-07-07", "2023-07-07"),
                ],
                null=True,
            ),
        ),
    ]
