# Generated by Django 4.2.2 on 2023-07-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0002_alter_schedule_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="patient",
        ),
        migrations.AddField(
            model_name="schedule",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="day",
            field=models.DateField(
                blank=True,
                choices=[
                    ("2023-07-01", "July 1, Saturday"),
                    ("2023-07-02", "July 2, Sunday"),
                    ("2023-07-03", "July 3, Monday"),
                    ("2023-07-04", "July 4, Tuesday"),
                    ("2023-07-05", "July 5, Wednesday"),
                    ("2023-07-06", "July 6, Thursday"),
                    ("2023-07-07", "July 7, Friday"),
                ],
                null=True,
            ),
        ),
    ]
