# Generated by Django 4.2.2 on 2023-07-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0003_remove_schedule_doctor_remove_schedule_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="phone",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
