# Generated by Django 4.2.2 on 2023-07-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0004_alter_schedule_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("08.00", "08.00"),
                    ("08.30", "08.30"),
                    ("09.00", "09.00"),
                    ("09.30", "09.30"),
                    ("10.00", "10.00"),
                    ("10.30", "10.30"),
                    ("11.00", "11.00"),
                    ("11.30", "11.30"),
                    ("12.00", "12.00"),
                    ("12.30", "12.30"),
                    ("13.00", "13.00"),
                    ("13.30", "13.30"),
                    ("14.00", "14.00"),
                    ("14.30", "14.30"),
                    ("15.00", "15.00"),
                    ("15.30", "15.30"),
                    ("16.00", "16.00"),
                    ("16.30", "16.30"),
                    ("17.00", "17.00"),
                    ("17.30", "17.30"),
                    ("18.00", "18.00"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
