# Generated by Django 4.2.2 on 2023-07-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0006_alter_schedule_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="status",
            field=models.CharField(
                choices=[("NOT_APPROVED", "Not Approved"), ("APPROVED", "Approved")],
                default="NOT_APPROVED",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("02/07/2023", "July 2, Sunday"),
                    ("03/07/2023", "July 3, Monday"),
                    ("04/07/2023", "July 4, Tuesday"),
                    ("05/07/2023", "July 5, Wednesday"),
                    ("06/07/2023", "July 6, Thursday"),
                    ("07/07/2023", "July 7, Friday"),
                    ("08/07/2023", "July 8, Saturday"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
