# Generated by Django 4.2.2 on 2023-07-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0007_schedule_status_alter_schedule_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("07/07/2023", "July 7, Friday"),
                    ("08/07/2023", "July 8, Saturday"),
                    ("09/07/2023", "July 9, Sunday"),
                    ("10/07/2023", "July 10, Monday"),
                    ("11/07/2023", "July 11, Tuesday"),
                    ("12/07/2023", "July 12, Wednesday"),
                    ("13/07/2023", "July 13, Thursday"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="phone",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("HELD", "Held"),
                ],
                default="PENDING",
                max_length=12,
            ),
        ),
    ]
