# Generated by Django 4.2.2 on 2023-07-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0008_alter_schedule_day_alter_schedule_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("08/07/2023", "July 8, Saturday"),
                    ("09/07/2023", "July 9, Sunday"),
                    ("10/07/2023", "July 10, Monday"),
                    ("11/07/2023", "July 11, Tuesday"),
                    ("12/07/2023", "July 12, Wednesday"),
                    ("13/07/2023", "July 13, Thursday"),
                    ("14/07/2023", "July 14, Friday"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
