# Generated by Django 4.2.2 on 2023-07-10 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_remove_patient_phone"),
        ("schedule", "0010_alter_schedule_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients",
                to="patients.patient",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("10/07/2023", "July 10, Monday"),
                    ("11/07/2023", "July 11, Tuesday"),
                    ("12/07/2023", "July 12, Wednesday"),
                    ("13/07/2023", "July 13, Thursday"),
                    ("14/07/2023", "July 14, Friday"),
                    ("15/07/2023", "July 15, Saturday"),
                    ("16/07/2023", "July 16, Sunday"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
